### ISSUE TITLE
Missing dependency - bs4

### ISSUE THREAD

**Issue by Cristi075** [N0rz3/TraxOsint#1]
After running 'pip3 install -r requirements.txt', bs4 was not installed but something uses it (so trying to run traxosint.py fails).

According to its [documentation](https://pypi.org/project/scrape-search-engine/), it looks like scrape-search-engine is the one that requires bs4

This can be fixed by adding 'beautifulsoup4' to the requirements.txt file

**Comment by Afolabi001** [comment]
pip install bs4

**Comment by N0rz3** [comment]
ah yes thank you I will add it immediately

**Comment by Afolabi001** [comment]
> ah yes thank you I will add it immediately

You are welcome
